kadi/events/models.py
kadi/update_events.py
kadi/version.py

After importing Kadi, I grab all the CAPS run from 2015:001 to 2015:
In [1]: from kadi import events
In [2]: capsrun = events.caps.filter('2015:001', '2015:026').table
Looking at the 14th row I see this:
In [3]: capsrun[13]
Out[3]: 
<Row 13 of table
values=(448701, '2015:008:00:43:24', '2015:007:23:40:03.303', 537065071.184, 537061270.487, -3800.697000026703, '1339', 'Command ACIS I CTI measurement via RTS', '', '', 'http://occweb.occ.harvard.edu/occweb/FOT/configuration/CAPs/1301_1400/')
dtype=[('ifot_id', '<i8'), ('start', '|S21'), ('stop', '|S21'), ('tstart', '<f8'), ('tstop', '<f8'), ('dur', '<f8'), ('num', '|S10'), ('title', '|S60'), ('descr', '|S1'), ('notes', '|S1'), ('link', '|S108')]>
Notice that start is after stop:
In [4]: capsrun[13]['start']
Out[4]: '2015:008:00:43:24'
In …

stop time is before start time

---

task_schedule_occ.cfg

Note that having the `--ftp` flag is OK even though the currently installed OCC version does not.

Fix task_schedule user and add an OCC version

---

kadi/update_events.py
kadi/version.py

The `update_archive.py` process was failing because the SQLite3 error message for a non-unique key changed between ActivePython sqlite3 and Anaconda Python sqlite3.  the word `unique` became upper case.
As a somewhat unrelated patch, fix `version.py` to not fail hard if there is no git executable.

Make IntegrityError message handling be case-insensitive

---

kadi/settings.py

Something like this should work:
```
OPTIONAL_APPS = ('mica.web', 'find_attitude')
for app in OPTIONAL_APPS:
try:
__import__(app)
except ImportError:
pass
else:
INSTALLED_APPS += app
```
@jeanconn - we discussed this before, don't remember if it ever got to the point of some code.

Make web-only apps optional

---

docs/make_field_tables.py
kadi/events/models.py

Add one shot break down (roll, pitch, yaw) to Manvr event
This PR adds the one_shot_roll, one_shot_pitch, and one_shot_yaw to the Manvr class.  A change is also made here to use the AOATTER values in the first guide readout, not the the values that correspond to the time when the RSS of AOATTER2 and AOATTER3 is biggest.

Add one shot break down (roll, pitch, yaw) to Manvr event

---

kadi/occweb.py
kadi/version.py

Was kadi ever passing occweb tests on Py3?  I'm confused because I thought ska_testr was OK on Ska3, but that isn't what I'm now seeing.
Anyway I noticed these test failures and so fixed the code to pass on Py3.
Closes #101

Py3 compatibility for occweb

---

kadi/update_events.py
kadi/version.py

This is a workaround for problems like:
```
2017-07-19 10:01:09,238 Updating Scs107 events from 2017:178:14:01:05 to 2017:200:14:01:04
2017-07-19 10:01:19,455 Deleting 34 LoadSegment events after 2017:180:14:01:04.585
Traceback (most recent call last):
File "/proj/sot/ska/share/kadi/update_events", line 12, in <module>
update_events.main()
File "/proj/sot/ska/arch/x86_64-linux_CentOS-6/lib/python2.7/site-packages/kadi/update_events.py", line 221, in main
update(EventModel, date_stop)
File "/proj/sot/ska/arch/x86_64-linux_CentOS-6/lib/python2.7/site-packages/kadi/update_events.py", line 100, in update
delete_from_date(EventModel, delete_date, set_update_date=False)
File "/proj/sot/ska/arch/x86_64-linux_CentOS-6/lib/python2.7/site-packages/kadi/update_events.py", line 72, in …
```

Work around issues with sqlite3 database being locked during updates

---

kadi/commands/states.py
kadi/commands/tests/test_states.py
kadi/version.py

- If the state-changing command was the last command, then that state got dropped and continuity got the wrong answer
- Query for continuity crashed for times far in the future (where the first 7-day lookback got no commands
@jeanconn - when you have a chance next week please review and (hopefully) merge and install to Ska HEAD flight, test, ska3 flight and GRETA test and ska3.
Ran self tests in ska and ska3 on kadi.

Fix a couple of issues in continuity

---

NOTES.web-test-install.rst
kadi/settings.py
kadi/tests/test_events.py
kadi/version.py

**Rationale**
This bug-fix patch eliminates the issue of accidentally creating or depending on config files in `$SKA/data/config`.
**Interface impact**
No change in user interface.
**Testing**
This PR passes relevant unit tests in Ska and Ska3.  It also passes a new test script that can only be run as a standalone script; it can't work as a pytest script (as far as I can tell) because it relies on updating the Python path prior to import kadi.
There is a new *unrelated* fail in `test_occweb.py` which is also now occurring in the installed version in Ska.  This is due to some issue with the lucky configuration, but since the relevant code `occweb.py` is unchanged, this unit test fail is OK.
**Review**
This has been reviewed by Jean Connelly and John Zuhone.
**Deployment**
This will be …

 Only set XDG_CONFIG_HOME in production web-server environment

---

kadi/cmds/tests/test_commands.py
kadi/commands/tests/test_commands.py
kadi/update_cmds.py
kadi/version.py

This also includes tweaks to `update_cmds.py` so that it generates cmds files using Ska3 (current /proj/sot/ska3/test 2018.08.02-a5c0a36) which pass tests.
**Update_cmds with /proj/sot/ska3/test**
**Update_cmds with /proj/sot/ska/flight**
- Wait for subsequent PR to make updates hourly.

 Add VCDU to commands archive and Py3 update capability

---

task_schedule_cmds.cfg
task_schedule_events.cfg
task_schedule_occ_cmds.cfg
task_schedule_occ_events.cfg

This removes check_cron from the more frequent job with the hope that
only the check_cront called in the "daily" events job will call watch_cron_logs and move
and check the logs.  You do run into the issue that the cmds logs will also
only be checked once a day (though a fatal error should still go to aca).
These edits also give each task a unique heartbeat file name to avoid collision.

Update task schedules for the two jobs to avoid conflicts

---

task_schedule_cmds.cfg
task_schedule_occ_cmds.cfg

Remove unused 'check' blocks in cmds task_schedules
These were orphaned when we removed 'check_cron' from the cmds jobs.

Remove unused 'check' blocks in cmds task_schedules

---

kadi/version.py
task_schedule_events.cfg

@jeanconn - I did some testing locally on the implications of the `events.db3` file going missing or changing during an active session.
Testing:
- Copy $ska/data/kadi/events.db3 to a local version
- Truncate the local version in time to generate diffs that are obvious in query results
- Open a window with KADI=$PWD to point to local events.db3
- Open ipython and do queries to confirm truncated events
- In another window, cp $ska/data/events.db3 back to the local events.db3
- Confirm that in the original ipython, subsequent event queries still produce expected truncated results, including queries for models that I didn't do before.
- Quit ipython and restart, and confirm that the full (non-truncated) events.db3 is now being used.
As far as I can tell the file system does the right thing, …

Do event updates on a local copy and mv back

---

task_schedule_cmds.cfg
task_schedule_events.cfg

Using `lucky` as a gateway to push commands and events to the GRETA network has been overtaken by pulling from GRETA via rsync.  This is more reliable and simpler.
Note that `task_schedule_occ_{cmds,events}.cfg` are no longer running on GRETA since moving to Wayside.

Stop pushing to ftp in regular processing

---

kadi/update_cmds.py
kadi/version.py

Fixes for kadi update_cmds to run correctly on Py3.  Also includes minor flake8 fixes.  Just one non-trivial fix related to the diffing and a bytes/unicode issue.  (str() of a bytestring gives `b'blah'` not `blah`.)
```
ska  # LEGACY ska
cd ~/tmp/kadi-test
python /proj/sot/ska/share/update_cmds.py --start=2015:001 --stop=2015:030
```
```
ska3  # Activate ska3 environment
cd ~/git/kadi
git checkout py3-compat
cp ~/git/ska_testr/packages/kadi/write_events_cmds.py write_cmds.py
```
- Edit `write_cmds.py` to comment out writing the events and fix a Py3-compatibility
problem (os.path cannot take None in Py3)
```
rm cmds.*
./update_cmds.py --start=2015:001 --stop=2015:030 --mp-dir ~/ska/data/mpcrit1/mplogs
python write_cmds.py  --start=2014:001 --stop=2016:001
mkdir cmds-ska2
cd cmds-ska2
scp …
```

Update_cmds fixes for py3

---

kadi/update_cmds.py

This is a simple change to the ingest of non-load commands.  It makes the applicable date range for commands go out to the ingest `stop` date instead of the end of the last timeline.  The previous logic was incorrect since during an anomaly the last timeline is clipped so you don't get non-load commands in the kadi cmds archive.
This works, as demonstrated in these two notebooks:
- https://nbviewer.jupyter.org/urls/cxc.cfa.harvard.edu/mta/ASPECT/ipynb/kadi/test-nonload-update-cmds-dev.ipynb
- https://nbviewer.jupyter.org/urls/cxc.cfa.harvard.edu/mta/ASPECT/ipynb/kadi/test-nonload-update-cmds-4.18.1.ipynb

Fix ingest of non-load commands during a load stoppage (anomaly)

---

kadi/update_cmds.py
setup.py
task_schedule_cmds.cfg

The main changes are:
- Allow for mission planning dirs to be in $SKA/data/mpcrit1/mplogs
- Install cfg files into $CONDA_PREFIX/share/kadi
This should be included in a 4.19 release.
Passes unit tests on MacOS and linux.
See https://github.com/sot/task_schedule/pull/15 for testing details on linux and MacOS in an integrated env with dev versions of kadi, task_schedule, and watch_cron_logs.

Migrate update_cmds task_schedule to ska3 idiom

---

kadi/commands/states.py
kadi/commands/tests/test_states.py

The modern version of https://github.com/sot/cmd_states/pull/24.
Fixes https://github.com/sot/cmd_states/issues/23.

Add ACIS raw-mode SI modes to ACIS states

---

kadi/commands/tests/test_states.py

Fix a failing test.  See the code comment for details.

Fix test to run on Windows

---

kadi/commands/commands.py
kadi/commands/tests/test_commands.py

Don't entirely throw away starcat cmds  when `remove_starcat=True`, just toss the parameters.

Improve get_cmds_from_backstop

---

docs/commands_states.rst
kadi/commands/states.py
kadi/commands/tests/test_states.py

This adds a new state to track the ACIS FP temperature based on commands of the form `WSFTNEG*`.
This could have been done with far less new code by just adding a new `elif` block to the existing `ACISTransition` class.  However, the first `WSFTNEG` command in the commands table is in 2003, so querying states before then was crashing.  The current implementation puts in place a default of -121.0.

Add acisfp_setpoint state

---

kadi/commands/commands.py
kadi/commands/tests/test_commands.py

This will make code related to RLTT a bit cleaner because in that case one needs to get commands up to and *including* the RLTT stop time.
This should be used in https://github.com/sot/starcheck/pull/341/.
- Added new unit test

Add inclusive_stop kwarg to get_cmds

---

kadi/commands/states.py
kadi/commands/tests/test_states.py

It turns out to be a good thing to supply `cmds` and `start` and `stop` in `get_states()` (https://github.com/sot/starcheck/pull/344).
To do:
- https://github.com/sot/starcheck/pull/344

Allow start and stop in get_states() with cmds

---

kadi/cmds/tests/test_commands.py
kadi/commands/tests/test_commands.py
kadi/commands/tests/test_states.py
kadi/events/models.py
kadi/occweb.py
kadi/tests/test_events.py
kadi/tests/test_occweb.py
manual_test_cmds.py
validate/gratings/compare_grating_moves.py
validate/gratings/plot_grating.py

Non-controversial updates to dates for Chandra.Time 4.0+ compatibility, almost entirely in test files.

SHINY: update dates for Chandra.Time 4.0+

---

kadi/commands/commands.py
kadi/commands/tests/test_commands.py

I really don't recall why this option was there and why the default was True. From searching the sot org this only gets used in starcheck (using the previous default of removing star catalogs).  It doesn't matter there, but of all the places to toss out the star catalogs this one seems ironic.

Change default remove_starcat to False

---

kadi/commands/commands.py
kadi/commands/states.py
kadi/commands/tests/test_commands.py
kadi/commands/tests/test_states.py

This adds times (in CXC seconds) to states and commands.  In looking at real use cases these columns are typically needed and the impact of adding them by default is not so bad.
It also converts columns in the `CommandsTable` from bytes to unicode. I found that `Chandra.Time.date2secs` failed for bytes input.  This could be fixed, but that failure points to other subtle problems that can be encountered using bytestring values (even though astropy Table does a reasonable job of hiding that with the unicode sandwich).

SHINY: add times to states and commands outputs

---

kadi/commands/commands.py
kadi/commands/states.py
kadi/commands/tests/test_commands.py

This adds a helper method to convert CommandTable to list of dict.  This was useful for the ACIS review tools to get back to a format like Ska.ParseCM.
It also adds `tstart` and `tstop` to the continuity to make it look more like a `state0` dict.

Add helpers for compatibility with legacy commands / states code

---

kadi/events/__init__.py

In addition, set DJANGO_ALLOW_ASYNC_UNSAFE, to avoid exception seen running in Jupyter notebook: SynchronousOnlyOperation: You cannot call this from an async
context. 
See: https://stackoverflow.com/questions/59119396.
Made a jupyter notebook with a single cell:
```
from kadi import events
safe_modes = events.safe_suns
safe_modes.table
```
Before this PR that would generate the `SynchronousOnlyOperation` exception. After the PR it runs correctly and produces the expected output.
Fixes #171

Fix async problem of event query within Jupyter notebook

---

kadi/commands/states.py
kadi/commands/tests/test_states.py

This is a slightly subtle bug that showed up in https://github.com/acisops/acis_thermal_check/pull/30#issuecomment-665240053. When requesting states starting within a maneuver it could happen that `datestart > datestop` in the first state. The first `datestart` was incorrect, but otherwise the state values were good.  For example:
```
In [4]: sts = states.get_states('2017:207:23:35:00', '2017:208', state_keys=['pitch'])                                                                
In [5]: sts                                                                                                                                           
Out[5]: 
<Table length=6>
datestart              datestop           tstart        tstop           pitch        trans_keys
str21                 str21 …
```

Fix continuity and states for start within maneuver

---

.github/workflows/build.yml

workflow fix: conda channel update depends on mac os build as well

workflow fix: conda channel update depends on mac os build as well

---

NOTES.build
kadi/commands/commands.py
kadi/commands/states.py
kadi/update_cmds.py
utils/migrate_cmds_idx_32bit.py

The `idx` column in the `cmds.h5` file was unfortunately sized at unsigned 16-bit int (65536). This identifies unique command parameters. The initial estimate that this would be more than enough proved to be faulty and the number exceeded 65536 with the AUG1720 loads.
Key elements are:
- Changed from uint16 to int32 for the `idx` column.
- Added code to ensure that `idx=65536` is never used. This ensures that the current ska3-flight kadi version 5.2.0 runs correctly (in particular `get_cmds_from_backstop`) with the new files.
This PR includes a new utility script that was used to migrate the `cmds.h5` as of August 8 (which did not suffer from the overflow issue) to a new version. The script contains checks that the new and previous commands are identical except for the dtype of `idx`. …

Migrate cmds.h5 idx column from 16 to 32 bits

---

.github/workflows/docs.yml
docs/conf.py
kadi/commands/states.py

This PR changes the documentation to unify style among all ska packages. Documentation is always in the docs directory, with configuration in conf.py, and uses the ska theme.
This PR also includes trivial changes for documentation:
- `sphinx.ext.pngmath`
- Removing double-colon before code block

Unified documentation style

---

kadi/events/orbit_funcs.py
kadi/update_cmds.py

This continues the theme of making all required data for Ska3 be referenced from `$SKA/data`.
This changes the cmds update process to $SKA/data/mpcrit1 instead of /data/mpcrit1. This link is set up on HEAD and for standalone machines one can make an sshfs mount to the HEAD version.
Functional testing was the ska_testr kadi regression test which generates a new events and cmds database. I did not run this on linux but it will get run automatically by the dashboard.

Use $SKA/data/mpcrit1 not /data/mpcrit1

---

kadi/commands/commands.py

Fix the problem seen in shiny testing from Replan Central by trying up to 3 times to read the `cmds.h5` file.
```
File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace
...
File "H5FDsec2.c", line 941, in H5FD_sec2_lock
unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
```
@jeanconn also remembered a plan B of copying the `cmds.*` files to a temp dir for updating as done with events in #124.
I updated the code to force a bad filename since I don't know how to reproducibly generate the `resource unavailable` error.
```
In [1]: from kadi.commands import get_cmds                                                                                      
In [2]: cmds = …
```

Handle cmds.h5 resource unavailable error

---

kadi/commands/commands.py
kadi/commands/tests/test_commands.py

This PR does two things:
- Add a `ska_parsecm` flag to `CommandTable.as_list_of_dict` to provide better compatibility with code that had previously been using `Ska.ParseCM`.
- Adds a function `read_backstop` which is more consistent with the naming convention for similar functions (and in particular `parse_cm.read_backstop`. The `kadi.commands.read_backstop` function is preferred as it has a more performant data structure, but either are OK.  (And in fact the kadi version calls the parse_cm version under the hood).

Add Ska.ParseCM compatibility + read_backstop function

---

kadi/commands/tests/test_commands.py
kadi/update_cmds.py

The driver here is to use `ska_helpers.retry` to avoid the 'Resource temporarily unavailable' error seen occasionally when updating the cmds archive.  See also #196 for the "client-side" analog.
In order to test that this was working, I ported the regression test from `ska_testr/packages/kadi/test_regress.sh` into a unit test. In theory that ska_testr test can be removed (but it isn't hurting anything and runs quickly).
I forced the open file function to fail twice to see it fail and then subsequently succeed. This was done by calling this stub `tables_open_file` function instead of `tables.open_file`.
```
fail_count = 0
def tables_open_file(*args, **kwargs):
global fail_count
if fail_count < 2:
fail_count += 1
raise IOError()
else:
return tables.open_file(*args, **kwargs)
```
The output …

Add test of creating cmds archive and retry opening cmds.h5

---

kadi/commands/states.py
kadi/commands/tests/test_states.py

When the start time was between AOUPTARQ and AOMANUVR commands, this led to an exception because the code was trying to insert pseudo-commanding for that maneuver, but did not yet have a defined target attitude. This led to a failure in the maneuver generating code since it was being passed `None` for an attitude value.
Fixes #198

Fix bug getting states starting between AOUPTARQ and AOMANUVR

---

NOTES.build
kadi/events/models.py

This makes event processing robust to getting no applicable telemetry or events, thus allowing the start of the event database build process to be set to an early date like 1999:001.
The `events3.db3` database was rebuilt from scratch on kady using the updated `NOTES.build` instructions.
- Confirmed that key events like `Obsid` and `Manvr` showed the expected new events coinciding with the beginning of available CXC L0 engineering telemetry on 1999:204.
- No errors and only expected processing warnings.
With the merging of this the new events file will be copied to flight.
Used the `validate/write_events_cmds.py` script to write ECSV text files for each event type corresponding to two date ranges:
- 1999:240 - 2021:070 (expected to match)
- 1999:001 - 1999:240 (expected to have new …

Make kadi events complete from start of mission

---

kadi/settings.py

This PR changes the ALLOWED_HOSTS variable in Django settings so it includes all our common hostnames. Perhaps we should consider going over the configuration.

changed ALLOWED_HOSTS to include all host names we use.

---

NOTES.build

Inelegant fix to a problem in the events database noted by Scott B. The event has been removed from the flight database with the cited command on HEAD and GRETA.
- [n/a] Passes unit tests on MacOS, linux, Windows (at least one required)
After deleting that entry the bad dump is no longer there:
```
In [1]: from kadi import events                                                                                                             
In [2]: events.dumps.filter('2020:140')[0]                                                                                             
Out[2]: <Dump: start=2020:269:20:32:00.619 dur=213>
```

Add note about removing bad dump

---

kadi/events/__init__.py

This PR would Fix #201.
The way it is currently set up, `kadi` loads django if the DJANGO_SETTINGS_MODULE is not defined. The assumption is that, because django sets this variable during loading, if it is defined it means django is loaded. This fails when a child process is spawned, because the variable will be defined for children processes, but the children processes do no inherit the python module.
I added another condition for loading django. Namely, that the `manvrs` variable is not defined within `kadi.events`.
Possible things to do:
- remove the check for DJANGO_SETTINGS_MODULE
- does this check need to be made elsewhere?
- add a unit test case with the gist from #201 (or some other test involving spawned processes).
Fixes #

Make sure django is loaded if it is not already loaded

---

kadi/events/models.py
kadi/events/templates/events/event_list.html
kadi/events/views.py
kadi/settings.py

Fix the old issue https://github.com/sot/web-kadi/issues/2. The problem was that the template expects the first field to be the primary key. This PR takes the approach of just changing the field order to make that the case for `Orbit` events.
It also addresses the request to reverse the time order. This is done for all event types, which seems reasonable to me.
Lastly, this PR adds localhost to the ALLOWED_HOSTS list because the local server doesn't work without that.
Note: this is based on eed97c1 (Merge pull request #204 from sot/note-bad-dump) which is the commit before #202 that breaks using the local server.
- Ran a local server and verified that Orbit events can be selected from the list view and properly displayed in detail view.
- Confirmed that the sort order is reversed in all …

Improve list view and fix old web-kadi issue

---

kadi/commands/states.py
kadi/commands/tests/test_states.py

Per discussion on slack ("looking at the commands associated with the letg state key" in ska-dev on Aug 12), add a new intermediate state to the grating states to indicate the movement time between INSR and RETR.
Subsequent discussion revealed no user concerns about making this API change.

Grating move duration in commanded states

---

kadi/commands/states.py
kadi/commands/tests/test_states.py

This reverts all commits that went in PR 205. This is in view on the [failures in regression testing](https://icxc.cfa.harvard.edu/aspect/skare3/testr/releases/2021.12rc1/) due to this PR, and the fact that we want to get 2021.12 out with web server fixes.

Revert commits introduced in PR 205 (grating move duration)

---

kadi/commands/tests/test_states.py
validate/gratings/compare_grating_moves.py

This PR makes tiny changes to remove uses of a few deprecated dtypes (https://github.com/sot/skare3/issues/753).
Fixes #

remove use of deprecated np.str

---

kadi/settings.py

I am not sure yet that this is the right solution, but this is "a solution". What is your opinion?
When running regression tests, we get this warning:
```
WARNINGS:
?: (admin.W411) 'django.template.context_processors.request' must be enabled in DjangoTemplates (TEMPLATES) in order to use the admin navigation sidebar.
```
This PR does as the warning indicates and enables `django.template.context_processors.request` in settings, but we could also:
- ignore the warning
- see why this thing believes someone wants to use the navigation sidebar (is it used?)
Fixes #

fix warning

---

.github/workflows/flake8.yml
docs/api.rst
docs/commands_states.rst
docs/commands_v2.rst
docs/conf.py
docs/events.rst
kadi.cfg
kadi/__init__.py
kadi/commands/__init__.py
kadi/commands/command_sets.py
kadi/commands/commands.py
kadi/commands/commands_v1.py
kadi/commands/commands_v2.py
kadi/commands/core.py
kadi/commands/observations.py
kadi/commands/states.py
kadi/commands/tests/test_commands.py
kadi/commands/tests/test_states.py
kadi/config.py
kadi/paths.py
kadi/scripts/update_cmds_v2.py
kadi/tests/test_occweb.py
pytest.ini
utils/convert_nonload_to_csv.py
utils/migrate_cmds_to_cmds2.py
validate/compare-commands-v1-v2.ipynb

This PR implements the [command archive v2.0 concept](https://docs.google.com/document/d/1UZfcQvVdIBNb3XdJnO8Ra_d5Xt8x_FHLWgVHa2FvHyE/edit#).
This requires https://github.com/sot/parse_cm/pull/35.
- New `pprint_like_backstop` method on `CommandTable`
- Add a `time` column to the CommandTable returned by `get_cmds`
- Remove the `timeline_id` column and add a `source` column to the CommandTable.
- Access network resources (Google sheets, OCCweb) by default
- Add LOAD_EVENT pseudo-commands containing observation information
- Add `get_observations` and `get_starcats` functions.
- CommandTable string columns like `date` and `source` are kept in encoded ASCII `bytes` in the table instead of being converted to unicode for improved performance. The astropy Table "unicode-sandwich" machinery …

Implement commands archive v2.0 (beta release)

---

kadi/commands/command_sets.py
kadi/commands/tests/test_commands.py

There was a problem with the `Command not run` command set that was missed in testing. It had previously worked when the `cmds2.h5` was generated, but a subsequent change broke it, but this was not seen until I regenerated the commands now.
This PR fixes the problem and adds complete testing of all the allowed command sets.
Note: in order for tests to pass this is based off of #221 and the merge request is into that branch.
None.
Independent check of unit tests by Javier

Fix bug in command-not-run command set and test

---

kadi/commands/commands_v2.py

As noted in originally in slack there are cases where obsids in nominal schedules had two star catalogs / observations. E.g.
```
observations = Table(commands.get_observations(obsid=57244))
observations[['obs_start', 'obs_stop']]
<Table length=2>
obs_start              obs_stop      
str21                 str21        
--------------------- ---------------------
2009:068:08:40:02.068 2009:068:08:40:02.068
2009:068:08:54:32.010 2009:068:16:16:30.660
```
Then obsid=57245 had exactly the same observation info and star catalog. This was due to the obsid and NMM command happening at exactly the same time, but with the obsid *before* the NMM command. This causes the observation code to assign the second obsid prior (in command order) to the NMM command.
This PR looks through the commands for …

Fix misorders between obsid cmd and NMM cmd

---

docs/commands_states.rst
docs/commands_v2.rst
kadi/commands/__init__.py
kadi/commands/commands_v2.py
kadi/commands/observations.py
kadi/commands/states.py
kadi/commands/tests/test_commands.py
kadi/paths.py

This is hodge-podge PR that makes improvements related to getting star catalogs from the commands archive.
- Adds `get_starcats_as_table` function
- Changes API on `get_observations` and `get_starcats`. First three args are now `start=None, stop=None, *, obsid=None, ...`. This is more consistent with signatures for other methods in kadi commands.
- Adds file-based caching of star catalog data to greatly improve performance.
- Adds `as_dict` option to `get_starcats` to allow getting catalogs as plain Python dict instead of converting to `ACATable` objects. This is another performance-driven feature.
- Changes API to update start/stop date filtering in `get_observations` (and by proxy `get_starcats`) so the filtering is inclusive. That means any observation where `obs_start` / `obs_stop` …

Cache starcat and other goodies

---

kadi/events/models.py

This fixes a problem where new Major Events were being added to the HTML source tables more than the default lookback time of 21 days. These events were then being lost.
By adding a 2-year `lookback` the code will see newly-added events as far back as 2 years. In addition the `lookback_delete` attribute means that *edits* of existing events (change/delete) can be done in that timeframe. In effect this will now maintain sync between the kadi events table and the source HTML pages.
**NOTE**
On `kady`, I already did a wholesale fix of the flight `MajorEvent` table with the following command. This was necessary to correct for this lookback bug over the entire time span, effectively re-syncing the database to the existing FOT and FDB major event HTML files:
- …

Remake last two years of MajorEvent table each time

---

docs/commands_states.rst
docs/commands_v2.rst
kadi/commands/__init__.py
kadi/commands/command_sets.py
kadi/commands/commands_v2.py
kadi/commands/observations.py
kadi/commands/tests/test_commands.py
kadi/paths.py

Add `starcat_date` to the parameters stored in observations.
Other things along the way:
- Noticed that the `clear_caches` was missing the OBSERVATIONS cache, so that was fixed.
- Noticed that the result from `get_observations` was a reference to the original params dicts in cache, so this allowed for shenanigans if the user played with those outputs. This, of course, came up in testing and took quite a while to figure out.
- Added some `clear_cache()` commands in certain tests to ensure independence of results from test order.
- Updated to run most of the `get_observations` or `get_starcats` test using the `flight` scenario so they will run on GRETA.
Also includes #225 and #226.
Fixes #220
- Adds a new key `starcat_date` to the dict returned by `get_observations`
- Changes the star …

Add starcat_date to observation parameters + fix caching and minor issues

---

kadi/occweb.py
kadi/tests/test_occweb.py

Another little convenience PR related to noodle, going along with https://github.com/sot/sparkles/pull/171. This allows the ``path`` for `get_occweb_dir` or `get_occweb_page` to start with one of the following Noodle paths:
- \\noodle\FOT
- \\noodle\GRETA\mission\Backstop
- \\noodle\vweb
None.
This PR was used in the functional testing for https://github.com/sot/sparkles/pull/171.

Allow OCCweb access using noodle path

---

docs/commands_states.rst

This adds setup instructions for creating `~/.netrc` to allow fetching recent command loads.
None
No code changes.
Built the docs with no sphinx warnings or errors and confirmed the docs look as expected.

Add instructions on creating .netrc

---

kadi/events/__init__.py

`ska_testr` integration showed a script that was expecting `EventQuery` to be available as an import from `kadi.events`, so this adds that in.
Fixes an unexpected API change where `EventQuery` was not available.
With `PYTHONPATH` set to the git repo at this branch, I ran `run_testr --include kadi`:
- Without the fix (current master) I reproduced the failure related to `EventQuery` seen in ska3-flight 2022.7rc2.
- With the fix all tests pass.

Add EventQuery to symbols exported from query.py by events/__init__.py

---

kadi/commands/commands_v2.py
kadi/commands/tests/test_commands.py

While looking at code for #244 I noticed this obvious mistake in the `clear_caches` implementation.
None

Fix a mistake in clear_caches

---

kadi/commands/command_sets.py
kadi/commands/tests/test_commands.py

The Bright Star Hold command set mistakenly contained the command to disable dither. This command does not actually happen in BSH so this PR removes the command.
None.
I confirmed using visual inspection with aca_view that dither is still enabled for the 2017:090 and 2022:223 BSH events.

Remove dither disable from bright star hold command set

---

kadi/commands/commands_v2.py

Fixes this problem, which likely won't be reproducible in the future because it depends on running about 20-30 days after day 2022:232.
```
from kadi.commands import states
tstart = '2022:140'
tstop = '2022:245'
keys = ['pitch', 'off_nom_roll', 'ccd_count', 'fep_count', 'clocking', 'vid_board', 'pcad_mode', 'simpos'] 
state_data = states.get_states(tstart, tstop, state_keys=keys, merge_identical=True)
```
Output:
```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
/var/folders/dy/fgd_00hx3t74rh7tfkw5btqw0000gn/T/ipykernel_7931/4291996280.py in <module>
4 tstop = '2022:245'
5 keys = ['pitch', 'off_nom_roll', 'ccd_count', 'fep_count', 'clocking', 'vid_board', 'pcad_mode', 'simpos']
----> …
```

Fix problem where starcat_date can be uninitialized

---

kadi/commands/commands_v2.py
kadi/commands/observations.py
kadi/paths.py

This makes a few improvements to the way star catalogs are handled in kadi commands:
Previously the last commanded star catalog was kept as "continuity" for subsequent observation. This is actually how the spacecraft works which was the original motivation, but in practice the way loads are built there is always a unique new catalog associated with the end of each maneuver (when auto-transition to NPNT is enabled).
What was happening in kadi was that a stale catalog was being assigned to maneuvers during anomaly recovery. The new behavior is that such an observation gets no catalog but logs a warning that no catalog was found when one was expected.
With the current flight version of `cmds2.h5` there were cases of multiple observations sharing the same star catalog. This no longer happens, …

Better star catalog handling

---

docs/commands_states.rst
docs/commands_v1.rst
docs/commands_v2.rst
kadi/commands/__init__.py
kadi/commands/commands_v1.py
kadi/commands/tests/test_commands.py
pytest.ini

This makes commands v2 the default and thus v1 is now the backup.
There are API changes that have been widely discussed in informational forums. In particular getting commands may try using network resources by default.
The new version of commands archive files generated with PR #248 should be installed into `$SKA/data/kadi` on HEAD when kadi commands v2 is promoted via a new ska3-flight release. Those files are in `/home/aldcroft/tmp/kadi` on HEAD.

Make commands v2 the default

---

kadi/commands/tests/test_commands.py

The cmds v2 archive was regenerated using version 7.0.0 with `migrate_cmds_to_cmds2.py`. Using this new file the unit tests pass (in particular the `create_archive` one for v2), except for the test that is fixed here.
This change is expected/desired because the observation in question previously had the *wrong* `starcat_date` associated with it. This obs was really a ground-commanded maneuver with a custom starcat that is not captured by the commands archive. Leaving the starcat as undefined is the right thing in this case.
Make a directory to store kadi archive files. From within that directory:
```
ln -s /proj/sot/ska/data/kadi/cmds-v7.0.x/cmds2.* ./
ln -s /proj/sot/ska/data/kadi/cmds.* ./
ln -s /proj/sot/ska/data/kadi/events3.db3 ./
export KADI=$PWD
```
Then run unit tests.
Independent …

Fix unit test failure for final v2 cmds

---

kadi/events/models.py

This fixes the problem with rad zones not showing up in Replan Central. The `Orbit` class which generates `rad_zones` was only accepting events up to the present. There might have been some issue with filtering the load date relative to the current time, so possibly the rad zones will start showing up on Tuesday.
In any case this fix makes `Orbit` look ahead to any loads that are in the SOT MP area.
On kady from the git directory:
```
ska3-kady$ python -m kadi.scripts.update_events --model Orbit
2022-10-03 20:20:21,948 ******************************************
2022-10-03 20:20:21,948 Running: /data/baffin/tom/git/kadi/kadi/scripts/update_events.py
2022-10-03 20:20:21,948 Version: 7.0.2.dev0+g73cd800.d20221004
2022-10-03 20:20:21,948 Time: Mon Oct …
```

Set lookforward for Orbit event class

---

kadi/commands/tests/test_commands.py
kadi/commands/tests/test_states.py
pytest.ini

For testing it is still allowed to import and use commands v1.
None
Using this branch with v7.0 version of the cmds2.* files passes `pytest` unit tests and does not issue any warning messages at the end.
If I change the `message=...` to something that does not match then I confirm the warnings are flagged by pytest.

Suppress v1 FutureWarning for testing

---

docs/commands_states.rst
kadi/commands/states.py
kadi/commands/tests/test_commands.py
kadi/commands/tests/test_states.py
kadi/occweb.py

In support of HRC operations and load review checking (in particular https://github.com/acisops/acis_thermal_check/pull/54), this adds three new HRC commanded state variables: `hrc_15v`, `hrc_i` and `hrc_v`. All three have state values of `OFF` or `ON`.
I regenerated the list of available commanded states in the documentation and found a few previously-added states that were not reflected in the docs.
A bug in the testing code was also discovered and fixed, namely that the fixture for temporarily setting the effective processing stop date was not clearing the commands cache at the end. This meant that subsequent tests were running with a truncated commands archive.
Finally, this PR cleans up a bunch of flake8 warnings related to line length.
None.

Add HRC states: 15v on, HRC-I on, HRC-S on

---

kadi/commands/states.py
kadi/commands/tests/test_states.py

When getting states (with no defined continuity) starting from just before a normal sun mode transition there was an exception due to the current attitude state quaternions being `None`. This PR fixes the issue ala #199 by dropping the NSM command and letting the next defined maneuver take over.
Fixes #258
No functional testing.  Unit test added.

Fix bug when getting states starting just before NSM

---

kadi/occweb.py
kadi/tests/test_occweb.py

Make life a little easier if a noodle path has the wrong case.

Make noodle path be case insensitive

---

kadi/commands/commands_v2.py

This removes the word `WARNING` from the logging text for a situation that is common in anomaly recovery scenarios. This will reduce unnecessary alerts in Ska job watch.
None
No testing given the scope of the change.

Remove WARNING in logging text

---

kadi/events/models.py

This adds `complete_intervals=True` to a key call to `logical_intervals` that defines the creation of kadi events. Previously this was relying on the default value of that kwarg being True. Since that default is being changed in https://github.com/sot/eng_archive/pull/243, here we need to be explicit.
While in the code I noticed that an ugly hack of the `@import_ska` decorator is no long needed now that the kadi package does not provide a web server. This hack doesn't play well with IDEs (code introspection doesn't work).
None.

Explicit complete_intervals=True in logical intervals + code tidy

---

kadi/commands/commands_v2.py
kadi/commands/tests/test_commands.py

This fixes a bug in the `get_cmds` query logic which resulted in missing commands from the query under somewhat unusual circumstances:
- Query start is between 30 to 44 days before current time
- Within that window there is a non-load command from a Command Event.
- Query start is later than that non-load command time + 3 days.
The basic problem is that the code was checking for the first command of any type in the recent commands. Instead it should have been checking for the first load command in recent commands (within 30 days).
The unit test demonstrates the problem as it applies for a current date of 2022:352. In this case the OORMPEN non-load command at 2022:312:03:09:55.000 causes the problem.
None
Added unit test which failed prior to the fix and passes now.
Independent check of …

Fix issue with cmd query around 30 days before current time

---

NOTES.events_maintain.rst

The documentation I wrote recently to update an existing kadi events database table didn't work this time around. I have no clue how it worked last time, but the new docs worked for me this morning. I was regenerating the updated `Dump` table in preparation for a new Ska3 release.
None
I followed the instructions and successfully updated the `Dump` event.

Fix event maintenance docs

---

kadi/commands/tests/test_commands.py

Remove a testing workaround

---

kadi/commands/commands_v2.py

Fix the problem in #276 by adding a keyword arg to the debug function to specify the logging level. In most cases a warning is appropriate (the default) but this particular situation is just informational.
Fixes #276
Before the patch this code would generate the informational output shown in #276 (circa 2023:048):
```
cmds = get_cmds(CxoTime.now())
```
After the patch this runs quietly. I also confirmed that with the patch if the `kadi.logger` is set to `"INFO"` log level then the expected INFO output appears.

Fix issue always logging about NSM during maneuver

---

setup.py
task_schedule_validate.cfg

This puts the new kadi commands validation into action.
Supercedes the Python 2 `validate_states` package version.
No code changes.
The new `task_schedule_validate.cfg` has been manually installed on HEAD and is now running as a regular cron job. The Py2 `validate_states` version is disabled. The Aspect Cron jobs page has been updated accordingly.
To do:

Add task_schedule_validate.cfg

---

kadi/events/query.py

This fixes the issue described in #283, but instead by ensuring that the `TZ` environment variable is not modified by the call to `django.setup()`. For most unix machines this means that `TZ` will be undefined, but on GRETA it will remain as `GMT`.
None
These tests use https://github.com/sot/cxotime/pull/36.
```
(ska3) ➜  kadi git:(master) ✗ env PYTHONPATH=/Users/aldcroft/git/cxotime ipython
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:27:35) [Clang 14.0.6 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.8.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import kadi.events
...: 
...: kadi.events.eclipses
Out[1]: <EventQuery: Eclipse>
In [3]: from cxotime import CxoTime
In [4]: t …
```

Ensure that timezone TZ env var is unmodified by `django.setup()`

---

kadi/commands/utils.py
kadi/commands/validate.py
kadi/scripts/validate_states.py
pytest.ini

This PR is paired with https://github.com/sot/cheta/pull/249 to factor out the `get_ofp_states` and `get_telem_values` functions into `cheta` where they more logically belong.
`get_ofp_states` and `get_telem_values` are no longer available in `kadi.utils`. Both of these are currently used only internally within `cheta` and `kadi` in SOT repos on GitHub. Any other usages in non-versioned tools can just be fixed.
The API for both of these were changed as well, hence it would not make sense to include a reference in `kadi.utils` (from cheta) for back-compatibility.
Validation script was run from inside the repo for the `branch` outputs and outside the repo for `release`. The `cheta` repository was checked out with …

Factor out `get_ofp_states` and `get_telem_values` for cheta #249 improvements

---

kadi/commands/tests/test_commands.py

This fixes some test failures on windows.
The following statement in the test
```
stop_date_2022_352 = stop_date_fixture_factory("2022:352")
```
causes the following error:
```
NotADirectoryError: [WinError 267] The directory name is invalid
```
The cause is the colon in the name, so this PR replaces the argument with an ISO date.
None

fix test on windows

---

kadi/commands/tests/test_commands.py

Compare regression test quaternions with delta-quat tolerance check instead of == test.
This fixes the issue that the calculated quaternions on fido present insignificant numeric differences from the same quaternions calculated on kady.
Independent check of unit tests by @taldcroft

Compare regression test quaternions with delta-quat tolerance check

---

kadi/commands/commands_v2.py

This gives a more useful error message for a common exception in the kadi commands archive.
None

Improve error message for stale local commands archive

---

kadi/commands/utils.py
kadi/commands/validate.py

This adds a state validator for the `sun_pos_mon` state.
It also fixes a bug where telemetry values with a trailing space character (e.g. `"ACT "`) do not match the state codes.
Adds a new plot in the state validation page.
From within the git repo:
```
python -m kadi.scripts.validate_states
```
This generated the following output: https://icxc.cfa.harvard.edu/aspect/test_review_outputs/kadi-pr292/

Add validator for sun position monitor

---

kadi/commands/commands_v2.py

Fixes log statements like:
```
2023-08-10 08:31:15,261 get_cmds: Getting commands from <chandra_time.Time.DateTime object at 0x7fa1eb0053f0> to <chandra_time.Time.DateTime object at 0x7fa1eb005600> for scenario=Non
e
```
On master at eb5868
```
In [1]: import kadi.commands.commands_v2
In [2]: kadi.commands.commands_v2.logger.setLevel('INFO')
In [4]: from Chandra.Time import DateTime
In [5]: cmds = kadi.commands.commands_v2.get_cmds(DateTime("2023:001"), DateTime("2023:005"))
2023-10-20 09:46:46,002 get_cmds: Getting commands from <chandra_time.Time.DateTime object at 0x1179b62f0> to <chandra_time.Time.DateTime object at 0x1179b7550> for scenario=None
2023-10-20 09:46:46,007 get_cmds: Getting commands from archive only because of: …
```

Update log statement with a time that prints

---

kadi/commands/command_sets.py

Use ska_helpers.utils.convert_to_int_float_str directly instead of parse_cm.common._coerce_type .
Stops warnings like
```
kadi/commands/tests/test_states.py: 1 warning
/fido.real/conda/envs/ska3-masters/lib/python3.10/site-packages/parse_cm/common.py:33: VisibleDeprecationWarning: The _coerce_type function is deprecated and will be removed in a future version of parse_cm. Use ska_helpers.utils.convert_to_int_float_str instead.
warnings.warn(
```
Tested in ska3-masters with https://github.com/sot/parse_cm/pull/44
Unit tests with and without this PR show no warning with PR and warning without and otherwise pass.

Use ska_helpers.utils.convert_to_int_float_str to stop Deprecation warns

---

kadi/commands/states.py

This is part of the [Performance project](https://github.com/orgs/sot/projects/7/views/1). It speeds up `get_states` by a factor of 2 to 3.
None
```
import time
import kadi
from kadi.commands import get_cmds
from kadi.commands.states import get_states
print(f"{kadi.__version__=}")
start, stop = "2021:001", "2022:001"
cmds = get_cmds(start, stop, scenario="flight")
t0 = time.time()
states = get_states(start, stop)
print(f"get_states took {time.time() - t0:.1f} sec")
t0 = time.time()
states = get_states(start, stop)
print(f"2nd get_states took {time.time() - t0:.1f} sec")
```
```
kadi.__version__='7.0.2'
get_states took 18.5 sec
2nd get_states took 18.1 sec
```
```
kadi.__version__='7.1.1.dev68+ge0dd365'
get_states took 5.5 sec
2nd get_states took 4.8 …
```

Performance improvement kadi states

---

docs/api.rst
docs/api_commands.rst
docs/api_events.rst
docs/api_states.rst
docs/api_validation.rst
docs/conf.py
kadi/__init__.py
kadi/commands/command_sets.py
kadi/commands/commands.py
kadi/commands/commands_v1.py
kadi/commands/commands_v2.py
kadi/commands/core.py
kadi/commands/observations.py
kadi/commands/states.py
kadi/commands/utils.py
kadi/commands/validate.py
kadi/events/models.py
kadi/events/query.py
kadi/occweb.py
kadi/scripts/update_cmds_v1.py

This converts all the docstrings to numpydoc style and refactors the API docs into separate files.
The automated update was done with below followed by some hand-edits to fix things up and make minor improvements along the way.
```
from skare3_tools.scripts import convert_numpydoc
convert_numpydoc.convert_directory_to_numpydoc("kadi")
```
```
(ska3-perf) ➜  kadi git:(numpydoc) git rev-parse HEAD
c2c2b9c775b7d29919feea5bdd2411627c4554e8
(ska3-perf) ➜  kadi git:(numpydoc) pytest kadi             
==================================================== test session starts ====================================================
rootdir: /Users/aldcroft/git, configfile: pytest.ini
plugins: timeout-2.1.0, anyio-3.6.2
collected 199 items …
```

Convert docstrings to numpydoc style and refactor API docs

---

kadi/commands/validate.py

This is a critical fix that reverts a change made in #268. Unfortunately I did not appreciate what this actually meant and our testing does not cover this code at all. Without the fix the `kadi_validate_states` script fails to run at all.
I plan to add a unit test that does a regression test of the `validate` code, but in the meantime this PR uses functional testing.
None
```
(ska3-perf) ➜  kadi git:(revert-abstract-method) git rev-parse HEAD                  
b2e4f579b4ac6bee3be176c4d10272e07b310d4f
(ska3-perf) ➜  kadi git:(revert-abstract-method) pytest kadi
==================================================== test session starts ====================================================
rootdir: /Users/aldcroft/git, configfile: …
```

Revert the change to decorate `Validate.update_tlm` method

---

setup.py

Broaden setup.py package data glob to install pkl.gz and ecsv.gz test data.  This is a tiny fix for #300 .
Tested with a local ska3-masters but with this kadi PR "python setup.py installed".
Unit tests don't pass without this fix and show errors like
```
E           FileNotFoundError: validation regression data /fido.real/conda/envs/ska3-masters/lib/python3.10/site-packages/kadi/commands/tests/data/validators_2022297_5_True.pkl.gz not found.
E           Run `python -m kadi.commands.tests.test_validate` to generate it.
```

Broaden setup.py package data glob to install pkl.gz and ecsv.gz test data

---

kadi/commands/validate.py

This just moves to code to use a nicer pattern for cached properties. This required a slight change in when the exclude intervals are fetched from Google sheets.
The PR also makes one small out-of-scope change to remove the unused `update_tlm()` base method. That originally served a purpose but is no longer used.
Used local ska3-performance installation.
```
(ska3-perf) ➜  kadi git:(use-cached-property) git rev-parse HEAD             
87bf8716ac03e51bef60a2f53f21d609df3e67f9
(ska3-perf) ➜  kadi git:(use-cached-property) pytest kadi
==================================================== test session starts ====================================================
rootdir: /Users/aldcroft/git, configfile: pytest.ini
plugins: …
```

Use cached property in commands validation

---

kadi/cmds/cmds.py
kadi/commands/commands_v2.py
kadi/commands/core.py
kadi/commands/states.py
kadi/commands/tests/test_commands.py
kadi/commands/tests/test_states.py
kadi/commands/validate.py
kadi/events/models.py
kadi/events/orbit_funcs.py
kadi/events/plot.py
kadi/events/query.py
kadi/events/scrape.py
kadi/occweb.py
kadi/scripts/update_cmds_v1.py
kadi/scripts/update_events.py
kadi/tests/test_events.py
kadi/tests/test_occweb.py
manual_test_cmds.py
utils/migrate_cmds_to_cmds2.py
validate/gratings/compare_grating_moves.py
validate/write_events_cmds.py

Flatten namespace packages using automated script in development.
```
(ska3-perf) ➜  kadi git:(flatten-namespace-package-names) git rev-parse HEAD 
b4ba74572471814c165fc86ebb2c3d52010b8df9
(ska3-perf) ➜  kadi git:(flatten-namespace-package-names) pytest kadi
==================================================== test session starts ====================================================
rootdir: /Users/aldcroft/git, configfile: pytest.ini
plugins: timeout-2.1.0, anyio-3.6.2
collected 218 items                                                                                                         
kadi/commands/tests/test_commands.py ...........................................................................      [ 34%] …
```

flatten namespace package names

---

kadi/commands/core.py
kadi/commands/tests/test_commands.py

Fix, document, and test `CommandTable.get_rltt()` and `CommandTable.get_schedule_stop_time()`.
Fixes #306 
This is based off of `validate-finish-line` so all tests pass, but could be rebased and merged into master if need be.
I confirmed that `get_rltt()` is called many times in the testing so the coverage is good. The new test is the only time `get_scheduled_stop_time` gets covered.
```
(ska3-perf) ➜  kadi git:(fix-rltt-schedule-stop) git rev-parse HEAD
ead858540edf30ab55e4d127022e48f249e1af57
(ska3-perf) ➜  kadi git:(fix-rltt-schedule-stop) pytest     
==================================================== test session starts =====================================================
rootdir: /Users/aldcroft/git, configfile: …
```

Fix, document, and test get_rltt and get_schedule_stop_time

---

kadi/commands/command_sets.py
kadi/commands/commands_v2.py
kadi/commands/tests/test_commands.py

This PR provides a better way to handle HRC being disabled than adding a bunch of `Command not run` events. It follows the pattern from `Load not run` and `Observing not run`.
I have added this new event type to the FOT MP documentation page just to get it done with now. There is no danger of this accidentally getting into the flight Events Sheet.
Supports new HRC not run entry on Events Sheet.
```
➜  kadi git:(hrc-disable) git rev-parse HEAD                                                        
8158e773d3a87499373378d17a5e414fd669b46d
➜  kadi git:(hrc-disable) pytest
===================================================== test session starts ======================================================
rootdir: /Users/aldcroft/git, …
```

Add "HRC not run" event to handle HRC being disabled

---

kadi/commands/command_sets.py
kadi/commands/commands_v2.py
kadi/commands/core.py
kadi/commands/tests/test_commands.py
utils/make_hrc_disable_events.py

This improves the `Command` and `Command not run` event types in the Command Events Sheet.
The documentation states that a `Command` or `Command not run` can be copy/pasted from the backstop file.  In that format the parameters are comma-delimited, but the code was expecting space-delimited. In the flight Sheet we had only previously used a single parameter `TLMSID=...` so it never came up. The code now uses the `parse_cm` backstop parser and thus requires comma-delimited parameters.
This PR adds the capability (along with a number of tests) to include multiple parameters in the `Command not run` event to match only a single command. Previously only the `date` and `TLMSID` were actually being used to select the command(s) to ignore. For disabling HRC this turns out to select an additional …

Improve `Command` and `Command not run` events

---

kadi/commands/tests/test_validate.py
kadi/tests/test_occweb.py

Skip tests if internet is not available.
None
```
masters) ➜  kadi git:(skip-test) git rev-parse HEAD
b47f543e7f61acd180fda7b649e0358c8411f39b
```
```
(masters) ➜  kadi git:(skip-test) pytest
===================================================== test session starts =====================================================
rootdir: /Users/aldcroft/git, configfile: pytest.ini
plugins: timeout-2.1.0, anyio-3.6.2
collected 174 items                                                                                                           
kadi/commands/tests/test_commands.py ........sssss..ss...............................................ss...s......       [ 43%]
kadi/commands/tests/test_states.py …
```

Skip tests if internet is not available

---

kadi/commands/core.py

The `kadi.commands.core` function `load_ska_dir()` has been superceded by `parse_cm.paths.load_dir_from_load_name()`. This PR re-implements the kadi `load_ska_dir()` function as a call to `load_dir_from_load_name()` and issues a deprecation `FutureWarning`. 
This function is now deprecated and using it will cause unit tests to fail or issue warnings to the console.
From https://github.com/search?q=org%3Asot%20ska_load_dir&type=code it seems that only `mica` was using this (fixed in https://github.com/sot/mica/pull/288).
With https://github.com/sot/mica/pull/288 installed:
```
(razl) ➜  kadi git:(deprecate-ska-load-dir) git rev-parse HEAD  
1d6011d8e0cd5ba9a2babc8dc57b1755d5e465ff
(razl) ➜  kadi git:(deprecate-ska-load-dir) pytest …
```

Deprecate kadi load_ska_dir() in favor of parse_cm load_dir_from_load_name

---

kadi/events/models.py
kadi/occweb.py

This fixes a FutureWarning caused by using `np.str`. The code got much cleaner due to an improvement in `io.ascii` since this kadi code was written. Now the `converters` kwarg can just be a dict of types (exactly the same as the `types` kwarg here). See https://docs.astropy.org/en/stable/io/ascii/read.html#parameters-for-read.
In addition I added a docstring and removed mutable values as keyword defaults in `get_ifot`.
Fixes #320
The `types` dict option of `get_ifot` now requires that the type be specified as the actual type object (e.g. `str` or `np.int64`) instead of a `str` that is used in `getattr(np, type)`.
I searched the `sot` repo on GitHub and found no instances outside of kadi that used the `types` kwarg of `get_ifot`.
```
(ska3) ➜  kadi git:(numpy-str-deprecation) git rev-parse …
```

Fix numpy str FutureWarning and modernize get_ifot slightly

---

kadi/commands/command_sets.py
kadi/commands/states.py
kadi/commands/tests/test_commands.py

This adds two new command events for the Chandra Comment Events sheet:
- `Maneuver sun pitch`: maneuver to a specified absolute sun pitch angle
- `Maneuver sun rasl`: roll about sun line by specified angle
Note that this passes tests with or without https://github.com/sot/ska_sun/pull/37 which changes the sign convention of roll about the sun line. This is the case because the code applies the rasl using `apply_sun_pitch_yaw` and then measures the change using `get_sun_pitch_yaw`. Those use the same sign convention so `rasl2 - rasl1` is the same in both cases (with/without 37).
Closes #316
No code impacts but this adds new command events. When this is ready to merge I will update the FOT MP command events TWiki documentation to include the two new command event types.
Tested with …

Add command events to implement maneuver to pitch and roll about sun line

---

kadi/commands/states.py
kadi/commands/tests/test_states.py

The matching time threshold of 125 seconds between battery connect time and eclipse entry appears to be too low. Eclipses on 2024:043 and 2024:046 had a delta of 129 to 130 seconds. This results in the `sun_pos_mon` remaining disabled coming out of eclipse.
This PR changes that value to 135 sec. This has been confirmed as an acceptable value with FOT eng. See the email thread "Criteria for SPM auto-enable following eclipse" around 2024-Feb-17 for details.
None
```
(ska3) ➜  kadi git:(spm-eclipse-reenable-fix) git rev-parse HEAD                         
1ed12413410dbd49cf1adcf29ced7d5377aa44f1
(ska3) ➜  kadi git:(spm-eclipse-reenable-fix) pytest
========================================================== test session starts ==========================================================
platform …
```

Change time threshold for auto-enable of SPM following eclipse

---

kadi/commands/states.py
kadi/commands/tests/test_states.py

Some states require a callback function to determine the state transition value. That callback can depend on other state values. The existing code did not check that the state value was defined, in which case it would be `None`. In the case of #325 this would cause an exception. For the other state callbacks that are changed in this PR the existing code worked but somewhat accidentally.
I did an audit of all the callbacks. Callbacks with code like `if state["eclipse_enable_spm"]` were left unchanged since checking for `None` and returning would have the same effect.
Fixes #325 
None
```
(ska3) ➜  kadi git:(fix-state-callbacks) git rev-parse HEAD                                                        
dd36d606367998375d5f97eb0efb1b4141bbf31e
(ska3) ➜  kadi git:(fix-state-callbacks) pytest …
```

Fix state-dependent callbacks

---

.pre-commit-config.yaml
kadi/commands/observations.py
kadi/commands/states.py
kadi/commands/tests/test_commands.py
kadi/config.py
ruff.toml

This brings support for AGASC 1.8 to kadi `get_starcats`. Previously the code was hardwired to use `proseco_agasc_1p7.h5`.
This PR now uses either 1.7 or 1.8 to identify stars, depending on the observation date. The date cut-offs are encoded as configuration parameters that allow for uncertainty in the actual transition date:
```
if date < conf.date_start_agasc1p8_earliest:  # 2024-Jul-21
Use 1.7
elif date < conf.date_start_agasc1p8_latest:  # 2024-Jul-21 + 30 days
Try 1.8. If any stars are not ID'd then use 1.7.
else:
Use 1.8
```
The method `observations.get_agasc_cone_fast()` was refactored to allow `agasc.get_agasc_cone(..., cache=True)` to do most of the work.
In addition some unrelated ruff updates were done.
- https://github.com/sot/agasc/pull/183
None.
```
(ska3) ➜  kadi …
```

Support AGASC 1.8 in `get_starcats`, refactor get_agasc_cone_fast()

---

kadi/commands/tests/test_commands.py

Set log leve to CRITICAL when calling the test function. Otherwise a message with WARNING gets logged and this causes a ska testr failure.
This PR supercedes:
- https://github.com/sot/ska_testr/pull/80.
- https://github.com/sot/ska_helpers/pull/58
```
(ska3) ➜  kadi git:(quiet-starcat-only-agasc1p8-test) env PYTHONPATH=/Users/aldcroft/git/ska_helpers pytest -k test_get_starcat_only_agasc1p8 -sv
============================================ test session starts ============================================
platform darwin -- Python 3.11.8, pytest-7.4.4, pluggy-1.4.0 -- /Users/aldcroft/miniconda3-arm/envs/ska3/bin/python3.11
cachedir: .pytest_cache
rootdir: /Users/aldcroft/git
configfile: pytest.ini
plugins: timeout-2.2.0, anyio-4.3.0
collected 182 items / 181 deselected / 1 selected …
```

Squelch logging warning message in one test

---

.pre-commit-config.yaml
kadi/commands/commands_v2.py
kadi/commands/states.py
ruff.toml

Update to use ska_sun.get_nsm_attitude
Requires https://github.com/sot/ska_sun/pull/38
```
(ska3) flame:kadi jean$ git rev-parse HEAD
63db05639fb2f35d169a1248ace40e602b2f25bd
(ska3) flame:kadi jean$ pytest -vs
================================================================ test session starts =================================================================
platform darwin -- Python 3.11.8, pytest-8.0.2, pluggy-1.4.0 -- /Users/jean/miniconda_m1/envs/ska3/bin/python3.11
cachedir: .pytest_cache
rootdir: /Users/jean/git
configfile: pytest.ini
plugins: timeout-2.2.0, anyio-4.3.0
collected 182 items                                                                                                                                  
kadi/commands/tests/test_commands.py::test_find PASSED …
```

Update to use get_nsm_attitude

---

kadi/commands/observations.py
kadi/commands/tests/test_commands.py
kadi/config.py

This uses a single date for the AGASC 1p7-1p8 promotion. Note that this is based on the branch of #332. It leaves the logic to be able to change the AGASC catalog file when getting star catalogs.
The main reason for this is that, even though the promotion dates are configurable parameters, the result also depends on whether the 1p8 file is present in `$SKA/data/agasc` or not, which means the parameters are not enough to guarantee reproducible results. With that out the window, a single date is as good, with simpler code.
This PR has the lint errors that are fixed in PR #336.

Use single date for agasc1p8 promotion

---

setup.py

Fixes the regex to specify the package data.
```
In [1]: import kadi
In [2]: kadi.test()
============================================== test session starts ===============================================
platform darwin -- Python 3.11.8, pytest-8.0.2, pluggy-1.4.0
PyQt5 5.15.9 -- Qt runtime 5.15.8 -- Qt compiled 5.15.8
rootdir: /Users/jean/miniforge3/envs/ska3-flight-latest/lib/python3.11/site-packages
plugins: astropy-0.11.0, qt-4.4.0, cov-5.0.0, timeout-2.2.0, remotedata-0.4.1, anyio-4.3.0, filter-subpackage-0.2.0, doctestplus-1.2.1, astropy-header-0.2.2, arraydiff-0.6.1, mock-3.14.0
collected 181 items
kadi/commands/tests/test_commands.py .......s............................................................. [ 38%]
...........s …
```

fix package data regex

---

kadi/commands/tests/test_commands.py

Fix a latent test failure due to there being an SCS-107 run in the first four days of 2025. The test assumes a normal load run for that time frame. Instead of trying to be clever, this fix just stipulates that running this test for years 2003 to 2024 inclusive is sufficient.
None.
```
(ska3) ➜  kadi git:(fix-starcats-each-year-test) git rev-parse --short HEAD
02aa65a
(ska3) ➜  kadi git:(fix-starcats-each-year-test) pytest
================================================================== test session starts ==================================================================
platform darwin -- Python 3.11.8, pytest-7.4.4, pluggy-1.4.0
rootdir: /Users/aldcroft/git
configfile: pytest.ini
plugins: cov-5.0.0, timeout-2.2.0, anyio-4.3.0
collected 182 items …
```

Limit testing of starcats each year to 2003-2024

---

kadi/commands/tests/test_commands.py
kadi/commands/tests/test_states.py
kadi/tests/test_occweb.py

This is a change intended for skare3 > 2025.0, where we will use astropy 7.0. It replaces uses of `Table.pformat_all()` wih `Table.pformat()`. This silences a warning.
```
============================================================= test session starts =============================================================
platform darwin -- Python 3.12.8, pytest-8.3.4, pluggy-1.5.0
rootdir: /Users/javierg/SAO/git
configfile: pytest.ini
plugins: anyio-4.7.0, timeout-2.3.1
collected 182 items                                                                                                                           
kadi/commands/tests/test_commands.py .................................................................................s                 [ 45%]
kadi/commands/tests/test_states.py …
```

replace uses of pformat_all with pformat

---

.pre-commit-config.yaml
kadi/commands/commands_v2.py
kadi/commands/core.py
kadi/commands/states.py
kadi/commands/tests/test_states.py

Replan Central `make_timeline.py` had a one-off uncaught exception (see below) related to trying to interpolate states at a time outside of the states intervals. Tracking this down is a little tricky since it was not reproducible, but `interpolate_states` can be fixed.
`interpolate_states` already uses `states[0]` for any `times` that are before the first state. This PR effectively clips the `times` so that it uses `states[-1]` for any `times` after the last state. This matches the default behavior of `np.interpolate()`.
```
WARNING - '/proj/sot/ska3/flight/share/arc3/make_timeline.py --data-dir=/proj/sot/ska3/flight/data/arc3' returned non-zero status: 256
Traceback (most recent call last):
File "/proj/sot/ska3/flight/share/arc3/make_timeline.py", line 714, in main
write_states_json( …
```

Clip times in interpolate_states

---

docs/commands_states/commands_details.rst
kadi/commands/commands_v2.py
kadi/commands/core.py
kadi/commands/states.py
kadi/commands/tests/test_commands.py
kadi/commands/tests/test_validate.py

This changes kadi to follow the convention in https://github.com/sot/cxotime/pull/50 of mocking the current time using the `CXOTIME_NOW` environment variable. This PR retains support for the now-deprecated `KADI_COMMANDS_DEFAULT_STOP` env var for back-compatibility, but the tests and docs are changed to use `CXOTIME_NOW`.
The initial goal had been that https://github.com/sot/cxotime/pull/50 would "just work", but it turns out some of the logic in kadi commands is a bit intricate. This PR does the minimal change to support `CXOTIME_NOW` without touching any code logic.
- https://github.com/sot/cxotime/pull/50
Using `KADI_COMMANDS_DEFAULT_STOP` now generates a warning.
```
(ska3-flight-2025.0rc2) ➜  kadi git:(use-cxotime-now-for-default-stop) git rev-parse --short HEAD          
1adfd04 …
```

Use CXOTIME_NOW, deprecate KADI_COMMANDS_DEFAULT_STOP for default stop

---

kadi/commands/command_sets.py
kadi/commands/tests/conftest.py
kadi/commands/tests/test_commands.py
kadi/commands/tests/test_validate.py
kadi/config.py

The DEC2324 load was interrupted by a radiation shutdown, in the middle of an HRC-S observation. SCS-107 should power the HRC off. 
The `cea_check` run for the JAN0325 return-to-science loads incorrectly indicated that the HRC was on at the beginning of the load, which resulted in a thermal violation. This PR ensures that the HRC is turned off from the perspective of kadi states. 
This includes an unrelated fix to one regression test `test_get_starcats_each_year`. This was failing in 2025 because the first 4 days include an SCS-107 run. I think that testing a fixed set of years 2003 to 2024 inclusive is fine.
This should NOT be installed to flight prior to Feb 15. Otherwise this will result in duplication of the same commands which are in the Command Events sheet. Kadi command processing …

[bugfix] Add commands to turn HRC off to SCS 107

---

docs/commands_states/index.rst
kadi/commands/commands_v2.py
kadi/commands/core.py
kadi/commands/observations.py
kadi/commands/states.py
kadi/commands/tests/conftest.py
kadi/commands/tests/test_commands.py
kadi/commands/tests/test_filter_events.py
kadi/config.py

This PR adds infrastructure to filter command events to get alternate command history:
- New `event_filter` kwarg in `get_cmds`, `get_states`, `get_continuity`, `get_observations`, 
`get_starcats`, `get_starcats_as_table` functions.
- `event_filter` is a function that takes a command events table (e.g. from the google sheet) and 
returns a boolean mask that selects events to keep.
- Event filtering functions to facilitate the process, most notably `filter_scs107_events` that removes
events normally associated with an SCS-107 run.
Adding this event filtering was not initially compatible with the caching mechanism for recent commands (within the last 30 days). Previously the cache key was just the `scenario`, but this did not account for changes to:
- `CXOTIME_NOW` current time mocking
- …

Add infrastructure to filter command events to get alternate command history

---

.pre-commit-config.yaml
kadi/commands/commands_v2.py
kadi/commands/states.py
kadi/commands/tests/test_commands.py

PR #351 introduced a problem in kadi commands update processing where the lookback value (None by default) was being used in a computation prior to being set to the `conf.default_lookback` value. This was temporarily fixed in production by adding the `--lookback=30` flag to the script command.
This PR does two things:
- Move the `lookback` update to the top of the function before it gets used.
- Change the test of the command archive update process to not supply the `--lookback` argument. This matches the way the script is called in production.
This PR also includes an unrelated fix for ruff 11.0. There are no code changes so I did not re-run unit tests.
None
With only the 1st commit, the `test_commands_create_archive_regress` test fails with the same exception seen in production …

Fix issue setting the lookback default after it gets used

---

kadi/events/scrape.py
kadi/tests/test_occweb.py

Parse major events html from 23-Apr-2025.
I'm not sure what changes were introduced last week, but today it looks like the parser was reading a containing layout table instead of the major events table, and then also failing on the last row (which is empty).  This PR uses the "Major Events:" span label to find the major event html table and skips rows that don't have YYYY:DOY values in the first column.
Parser in master is doing this today:
```
In [1]: import kadi.events.scrape
In [2]: evts = kadi.events.scrape.get_fot_major_events()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/miniforge3/envs/ska3-latest/lib/python3.12/site-packages/chandra_time/Time.py:644, in …
```

Parse major events html from 23-Apr-2025

---

kadi/commands/tests/test_commands.py
kadi/commands/tests/test_states.py
ruff-base.toml

Update to conditionally skip some tests that fail without internet.
Fixes
```
FAILED kadi/commands/tests/test_commands.py::test_get_cmds_from_event_all[4] - requests.exceptions.ConnectionError: HTTPSConnectionPool(host='occweb.cfa.harvard.edu', port=443): Max retries exceeded with url: /occweb/FOT...
FAILED kadi/commands/tests/test_states.py::test_regression[kadi/commands/tests/data/regression/hrc_i-2024360-2025030.ecsv] - AssertionError: State tables have different lengths
FAILED kadi/commands/tests/test_states.py::test_regression[kadi/commands/tests/data/regression/hrc_s-2024360-2025030.ecsv] - AssertionError: State tables have different lengths
FAILED kadi/commands/tests/test_states.py::test_regression[kadi/commands/tests/data/regression/hrc_15v-2024360-2025030.ecsv] - AssertionError: …
```

Update to conditionally skip some tests that fail without internet
