NOTES.web-install.rst, NOTES.web-test-install.rst, kadi/settings.py, kadi/templates/base.html, kadi/urls.py
The 'web' branch with a collection of kadi web server enhancements.
=> Kadi web enhancements

kadi/settings.py
This fixes a couple of annoyances/problems when importing kadi.
=> Startup issues

kadi/templates/base.html, kadi/urls.py
=> Add mica star history app

kadi/tests/test_occweb.py
Add some lightweight tests to check occweb http fetches
=> Add some lightweight tests to check occweb http fetches

kadi/tests/test_occweb.py
Fix ftp test bug.  'login' is the user key in netrc
=> Fix ftp test bug.

NOTES.reprocess
=> Add notes on reprocessing kadi events archive

NOTES.web-test-install.rst
Simplified this down to just the necessary steps for the current configuration.
=> Update notes on installing kadi for the kadi web app

kadi/version.py
This commit was installed to flight but didn't seem to have made it to master.
=> Update to version 3.13.0

NOTES.add_event_type
Update kadi event update notes based on 3.14 experience
=> Update kadi event update notes based on 3.14 experience

kadi/commands/tests/test_states.py, kadi/version.py
Update tests in kadi.commands for the WSVIDALLDN ccd_count change.
=> Update tests for last bugfix

kadi/commands/commands.py, kadi/commands/states.py, kadi/commands/tests/test_commands.py
=> Add backstop handling to kadi.commands

kadi/version.py
=> Updated version to 4.18.1

kadi/commands/tests/test_states.py
Update mid-manvr test to use column comparisons and isclose
=> Update mid-manvr test to use column comparisons and isclose

.git_archival.txt, .gitattributes
=> Add .gitattributes and .git_archival.txt for setuptools_scm use

.github/workflows/flake8.yml, kadi/commands/commands.py, kadi/events/models.py
Fixes some problems noted by a newer version of flake8.
=> Fix flake8 issues

.github/workflows/build.yml, .github/workflows/release.yml
=> Shiny Workflow

.github/workflows/build.yml
sorry about that. Trivial fix.
=> Shiny Workflow fixup

.github/workflows/build.yml
mkdir should not fail if directory exists
=> Workflow fix

.github/workflows/build.yml
added windows build workflow
Fixes #
=> added windows build workflow

.github/workflows/build.yml
artifact name changed from package to conda-package
Fixes #
=> Workflow fixup: artifact name

.github/workflows/build.yml
=> Workflow fix: artifact name

.github/workflows/build.yml
Workflow: update masters conda channel, not test
=> Workflow: update masters conda channel, not test

.github/workflows/build.yml
Workflow: arch-specific and using sot/setup-miniconda
=> Workflow: arch-specific and using sot/setup-miniconda

docs/conf.py
Trivial PR to fix the homepage URL in `conf.py`, and to see if the docs workflow triggers on a new release.
Changes (fixes) the link in the "skatools" icon in the docs page.
No code changes, tests not run.
Built docs locally and see the homepage URL update in local browser.
=> Update homepage URL

docs/event_descriptions.rst, docs/events.rst, docs/make_field_tables.py, kadi/events/models.py, kadi/events/query.py
Fixes some documentation issues noted by @Gregg140. This also updates the auto-doc generation script to work in Py3.
Fixes #235
Fixes #236
None.
No package code changes.
Built the docs and confirmed the expected updates.
=> Fix various doc issues

kadi/commands/tests/test_commands.py, kadi/commands/utils.py
This PR adds some `cxotime.units.day` in a few places to avoid warnings.
=> Time units

.pre-commit-config.yaml, kadi/commands/commands_v2.py
Update pre-commit config to latest black and isort, and then update code for compatibility.
No lines of code changed, just one black line removed.
=> pre-commit autoupdate
